language: python

python:
  - "2.6"
  - "2.7"
  # - "3.2"
  # - "3.3"

# command to install dependencies
install:
  - pip install -r requirements-dev.txt
  # Temporal solution to travis issue #155
  - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm

# command to run tests
script: tox && tox -e lint
